// AUTO-GENERATED by scripts/precompute-results.mjs — DO NOT EDIT MANUALLY
// Regenerate: node scripts/precompute-results.mjs

import { AnalysisResult } from './types';

export type DemoVideoKey = 'dummy-test.mov' | 'serious-test.mp4';
export type GranularityKey = 'general' | 'detailed';

export const PRECOMPUTED_DEMO_RESULTS: Record<DemoVideoKey, Record<GranularityKey, AnalysisResult>> = {
  "dummy-test.mov": {
    "general": {
      "transcript": "من خیلی عصبانی ام. I'm so angry. I'm so happy. I'm so happy.",
      "facialEmotions": [
        {
          "startTime": "00:00",
          "endTime": "00:01",
          "emotion": "Neutral",
          "confidence": 0.9
        },
        {
          "startTime": "00:01",
          "endTime": "00:05",
          "emotion": "Joy",
          "confidence": 0.95
        },
        {
          "startTime": "00:05",
          "endTime": "00:07",
          "emotion": "Joy",
          "confidence": 0.95
        },
        {
          "startTime": "00:07",
          "endTime": "00:08",
          "emotion": "Sadness",
          "confidence": 0.8
        },
        {
          "startTime": "00:08",
          "endTime": "00:11",
          "emotion": "Surprise",
          "confidence": 0.9
        },
        {
          "startTime": "00:08",
          "endTime": "00:11",
          "emotion": "Fear",
          "confidence": 0.7
        },
        {
          "startTime": "00:11",
          "endTime": "00:12",
          "emotion": "Sadness",
          "confidence": 0.8
        }
      ],
      "speechAnalysis": [
        {
          "startTime": "00:01",
          "endTime": "00:03",
          "text": "من خیلی عصبانی ام.",
          "sentiment": "Anger"
        },
        {
          "startTime": "00:05",
          "endTime": "00:07",
          "text": "I'm so angry.",
          "sentiment": "Anger"
        },
        {
          "startTime": "00:08",
          "endTime": "00:11",
          "text": "I'm so happy. I'm so happy.",
          "sentiment": "Joy"
        }
      ],
      "mismatches": [
        {
          "timestamp": "00:01-00:03",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anger",
          "severity": "HIGH"
        },
        {
          "timestamp": "00:05-00:07",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anger",
          "severity": "HIGH"
        },
        {
          "timestamp": "00:08-00:11",
          "visualEmotion": "Surprise",
          "verbalEmotion": "Joy",
          "severity": "HIGH"
        }
      ],
      "overallSummary": "The video demonstrates significant emotional incongruence. The speaker verbally expresses anger while displaying joy, and later expresses happiness while showing surprise and fear. This suggests a strong internal conflict or a deliberate attempt to mask true emotions, which is a key area for exploration in ISTDP and EFT."
    },
    "detailed": {
      "transcript": "من خیلی عصبانی ام. I'm so angry. I'm so happy. I'm so happy.",
      "facialEmotions": [
        {
          "startTime": "00:00",
          "endTime": "00:01",
          "emotion": "Neutral",
          "confidence": 0.9
        },
        {
          "startTime": "00:01",
          "endTime": "00:05",
          "emotion": "Joy",
          "confidence": 0.95
        },
        {
          "startTime": "00:05",
          "endTime": "00:07",
          "emotion": "Joy",
          "confidence": 0.95
        },
        {
          "startTime": "00:07",
          "endTime": "00:08",
          "emotion": "Sadness",
          "confidence": 0.8
        },
        {
          "startTime": "00:08",
          "endTime": "00:12",
          "emotion": "Surprise",
          "confidence": 0.9
        }
      ],
      "speechAnalysis": [
        {
          "startTime": "00:01",
          "endTime": "00:03",
          "text": "من خیلی عصبانی ام",
          "sentiment": "Anger"
        },
        {
          "startTime": "00:05",
          "endTime": "00:07",
          "text": "I'm so angry.",
          "sentiment": "Anger"
        },
        {
          "startTime": "00:08",
          "endTime": "00:10",
          "text": "I'm so happy.",
          "sentiment": "Joy"
        },
        {
          "startTime": "00:10",
          "endTime": "00:12",
          "text": "I'm so happy.",
          "sentiment": "Joy"
        }
      ],
      "mismatches": [
        {
          "timestamp": "00:01-00:03",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anger",
          "severity": "HIGH"
        },
        {
          "timestamp": "00:05-00:07",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anger",
          "severity": "HIGH"
        },
        {
          "timestamp": "00:08-00:10",
          "visualEmotion": "Surprise",
          "verbalEmotion": "Joy",
          "severity": "HIGH"
        },
        {
          "timestamp": "00:10-00:12",
          "visualEmotion": "Surprise",
          "verbalEmotion": "Joy",
          "severity": "HIGH"
        }
      ],
      "overallSummary": "The video exhibits significant emotional incongruence. The speaker verbally expresses anger while simultaneously displaying joy through a broad smile. Later, the speaker verbally expresses happiness while displaying a facial expression of surprise or distress (wide eyes, open mouth). These high-severity mismatches between verbal and visual emotional cues suggest a strong internal conflict or a defense mechanism where true feelings are being masked or disavowed. This pattern is crucial for exploration in therapeutic contexts like ISTDP and EFT, indicating a potential struggle with authentic emotional expression and regulation."
    }
  },
  "serious-test.mp4": {
    "general": {
      "transcript": "Yeah, I mean, they're lovely. I I I get on really well with them, but I don't know. I just recently whenever they want to go out or stuff, I just I don't want to bring them down. I can't, they don't understand what I'm going to, they kind of I don't know, they don't make fun of how I feel, but they don't really understand what it's like. I just I don't want to go out with them and bring them down or stuff. Okay. I mean, it's easier to hide it than to try and explain it all the time when no one really wants to know. Okay, so it's I don't really talk to my parents about either. Okay. So that's kind of hard. I guess it kind of started uh when I was actually when I was revising for my exams. Um, I guess the stress I put a lot of stress on myself. I think I've always wanted to do well for me and I guess for my parents, so the stress of exams and it was also kind of hard because my parents were going through a bit of a a trouble time then so. Sounds like that was a real shock to you. Yeah, I guess it was hard as well because I wasn't doing well at uni and I guess I just felt a bit guilty. I I know it sounds silly but I felt like maybe if I could do better then they would get better, but I don't know, it just wasn't really happening. Okay, so it sounds like you were trying to work hard and yeah, um, be more successful because you thought that that would make them happier and try and fix things. Yeah, I wanted to make them feel better, but it just kind of backfired a little, I guess. How did it backfire? Oh, it just ended up with them getting worse and I've just been feeling worse since then.",
      "facialEmotions": [
        {
          "startTime": "00:00",
          "endTime": "00:20",
          "emotion": "Joy",
          "confidence": 0.85
        },
        {
          "startTime": "00:20",
          "endTime": "00:40",
          "emotion": "Neutral",
          "confidence": 0.75
        },
        {
          "startTime": "00:40",
          "endTime": "01:00",
          "emotion": "Joy",
          "confidence": 0.8
        },
        {
          "startTime": "01:00",
          "endTime": "01:20",
          "emotion": "Joy",
          "confidence": 0.82
        },
        {
          "startTime": "01:20",
          "endTime": "01:40",
          "emotion": "Joy",
          "confidence": 0.88
        },
        {
          "startTime": "01:40",
          "endTime": "01:49",
          "emotion": "Joy",
          "confidence": 0.85
        }
      ],
      "speechAnalysis": [
        {
          "startTime": "00:00",
          "endTime": "00:30",
          "text": "Yeah, I mean, they're lovely. I I I get on really well with them, but I don't know. I just recently whenever they want to go out or stuff, I just I don't want to bring them down. I can't, they don't understand what I'm going to, they kind of I don't know, they don't make fun of how I feel, but they don't really understand what it's like. I just I don't want to go out with them and bring them down or stuff.",
          "sentiment": "Sadness"
        },
        {
          "startTime": "00:30",
          "endTime": "01:00",
          "text": "Okay. I mean, it's easier to hide it than to try and explain it all the time when no one really wants to know. Okay, so it's I don't really talk to my parents about either. Okay. So that's kind of hard. I guess it kind of started uh when I was actually when I was revising for my exams. Um, I guess the stress I put a lot of stress on myself. I think I've always wanted to do well for me and I guess for my parents, so the stress of exams and it was also kind of hard because my parents were going through a bit of a a trouble time then so.",
          "sentiment": "Anxiety"
        },
        {
          "startTime": "01:00",
          "endTime": "01:30",
          "text": "Sounds like that was a real shock to you. Yeah, I guess it was hard as well because I wasn't doing well at uni and I guess I just felt a bit guilty. I I know it sounds silly but I felt like maybe if I could do better then they would get better, but I don't know, it just wasn't really happening.",
          "sentiment": "Guilt"
        },
        {
          "startTime": "01:30",
          "endTime": "01:49",
          "text": "Okay, so it sounds like you were trying to work hard and yeah, um, be more successful because you thought that that would make them happier and try and fix things. Yeah, I wanted to make them feel better, but it just kind of backfired a little, I guess. How did it backfire? Oh, it just ended up with them getting worse and I've just been feeling worse since then.",
          "sentiment": "Sadness"
        }
      ],
      "mismatches": [
        {
          "timestamp": "00:00 - 00:20",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "00:20 - 00:40",
          "visualEmotion": "Joy",
          "verbalEmotion": "Frustration",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "00:40 - 01:00",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anxiety",
          "severity": "HIGH"
        },
        {
          "timestamp": "01:00 - 01:20",
          "visualEmotion": "Joy",
          "verbalEmotion": "Guilt",
          "severity": "HIGH"
        },
        {
          "timestamp": "01:20 - 01:40",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "HIGH"
        },
        {
          "timestamp": "01:40 - 01:49",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "HIGH"
        }
      ],
      "overallSummary": "The speaker consistently maintains a cheerful or neutral facial expression, often accompanied by a smile, throughout the conversation. However, the verbal content reveals significant underlying emotional distress, including sadness, frustration, anxiety, and guilt. There is a strong and persistent mismatch between her positive facial presentation and the negative emotional themes in her speech, particularly when discussing stressful topics like academic performance and parental difficulties. This incongruence suggests a tendency to mask her true feelings, indicating an internal conflict where she attempts to appear strong or unaffected despite experiencing considerable emotional turmoil."
    },
    "detailed": {
      "transcript": "Yeah, I mean, they're lovely. I I I get on really well with them, but I don't know. I just recently whenever they want to go out or stuff, I just I don't want to bring them down. I can't, they don't understand what I'm going to, they kind of I don't know, they don't make fun of how I feel, but they don't really understand what it's like. I just I don't want to go out with them and bring them down or stuff. Okay. I mean, it's easier to hide it than to try and explain it all the time when no one really wants to know. Okay, so it's I don't really talk to my parents about either. Okay, so that's kind of hard. I guess it kind of started uh when I was actually when I was revising for my exams. Um, I guess the stress I put a lot of stress on myself. I think I've always wanted to do well for me and I guess for my parents, so the stress of exams and it was also kind of hard because my parents were going through a bit of a a trouble time then so. I was like that was a real shock to you. Yeah, I guess it was hard as well because I wasn't doing well at uni and I I guess I just felt a bit guilty. I I know it sounds silly but I felt like maybe if I could do better then they would get better but I don't know, it just wasn't really happening. Okay, so it sounds like you were trying to work hard and yeah, um, be more successful because you thought that that would make them happier and try and fix things. Yeah, I wanted to make them feel better but it just kind of backfired a little I guess. How did it backfire? Well, it just ended up with them getting worse and I've just been feeling worse since then.",
      "facialEmotions": [
        {
          "startTime": "00:00",
          "endTime": "00:05",
          "emotion": "Joy",
          "confidence": 0.8
        },
        {
          "startTime": "00:05",
          "endTime": "00:10",
          "emotion": "Neutral",
          "confidence": 0.6
        },
        {
          "startTime": "00:10",
          "endTime": "00:15",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "00:15",
          "endTime": "00:20",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "00:20",
          "endTime": "00:24",
          "emotion": "Sadness",
          "confidence": 0.6
        },
        {
          "startTime": "00:24",
          "endTime": "00:29",
          "emotion": "Neutral",
          "confidence": 0.6
        },
        {
          "startTime": "00:29",
          "endTime": "00:34",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "00:34",
          "endTime": "00:39",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "00:39",
          "endTime": "00:44",
          "emotion": "Neutral",
          "confidence": 0.6
        },
        {
          "startTime": "00:44",
          "endTime": "00:49",
          "emotion": "Anxiety",
          "confidence": 0.7
        },
        {
          "startTime": "00:49",
          "endTime": "00:54",
          "emotion": "Anxiety",
          "confidence": 0.7
        },
        {
          "startTime": "00:54",
          "endTime": "01:00",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "01:00",
          "endTime": "01:05",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "01:05",
          "endTime": "01:10",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "01:10",
          "endTime": "01:15",
          "emotion": "Guilt",
          "confidence": 0.7
        },
        {
          "startTime": "01:15",
          "endTime": "01:20",
          "emotion": "Hope",
          "confidence": 0.6
        },
        {
          "startTime": "01:20",
          "endTime": "01:25",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "01:25",
          "endTime": "01:30",
          "emotion": "Hope",
          "confidence": 0.6
        },
        {
          "startTime": "01:30",
          "endTime": "01:35",
          "emotion": "Guilt",
          "confidence": 0.7
        },
        {
          "startTime": "01:35",
          "endTime": "01:40",
          "emotion": "Sadness",
          "confidence": 0.7
        },
        {
          "startTime": "01:40",
          "endTime": "01:48",
          "emotion": "Sadness",
          "confidence": 0.8
        }
      ],
      "speechAnalysis": [
        {
          "startTime": "00:00",
          "endTime": "00:05",
          "text": "Yeah, I mean, they're lovely. I I I get on really well with them, but",
          "sentiment": "Joy"
        },
        {
          "startTime": "00:05",
          "endTime": "00:10",
          "text": "I don't know. I just recently whenever they want to go out or stuff, I just",
          "sentiment": "Frustration"
        },
        {
          "startTime": "00:10",
          "endTime": "00:15",
          "text": "I don't want to bring them down. I can't, they don't understand what I'm going to, they kind of",
          "sentiment": "Guilt"
        },
        {
          "startTime": "00:15",
          "endTime": "00:20",
          "text": "I don't know, they don't make fun of how I feel, but they don't really understand what it's like.",
          "sentiment": "Frustration"
        },
        {
          "startTime": "00:20",
          "endTime": "00:24",
          "text": "I just I don't want to go out with them and bring them down or stuff.",
          "sentiment": "Guilt"
        },
        {
          "startTime": "00:24",
          "endTime": "00:29",
          "text": "Okay. I mean, it's easier to hide it than to try and explain it all the time when",
          "sentiment": "Sadness"
        },
        {
          "startTime": "00:29",
          "endTime": "00:34",
          "text": "no one really wants to know. Okay, so it's",
          "sentiment": "Resignation"
        },
        {
          "startTime": "00:34",
          "endTime": "00:39",
          "text": "I don't really talk to my parents about either. Okay, so that's kind of hard.",
          "sentiment": "Sadness"
        },
        {
          "startTime": "00:39",
          "endTime": "00:44",
          "text": "I guess it kind of started uh when I was actually when I was revising for my exams.",
          "sentiment": "Neutral"
        },
        {
          "startTime": "00:44",
          "endTime": "00:49",
          "text": "Um, I guess the stress I put a lot of stress on myself. I think",
          "sentiment": "Anxiety"
        },
        {
          "startTime": "00:49",
          "endTime": "00:54",
          "text": "I've always wanted to do well for me and I guess for my parents, so the stress of exams",
          "sentiment": "Anxiety"
        },
        {
          "startTime": "00:54",
          "endTime": "01:00",
          "text": "and it was also kind of hard because my parents were going through a bit of a",
          "sentiment": "Sadness"
        },
        {
          "startTime": "01:00",
          "endTime": "01:05",
          "text": "a trouble time then so. I was like that was a real shock to you.",
          "sentiment": "Shock"
        },
        {
          "startTime": "01:05",
          "endTime": "01:10",
          "text": "Yeah, I guess it was hard as well because I wasn't doing well at uni and I",
          "sentiment": "Guilt"
        },
        {
          "startTime": "01:10",
          "endTime": "01:15",
          "text": "I guess I just felt a bit guilty. I I know it sounds silly but I felt",
          "sentiment": "Guilt"
        },
        {
          "startTime": "01:15",
          "endTime": "01:20",
          "text": "like maybe if I could do better then they would get better but",
          "sentiment": "Sadness"
        },
        {
          "startTime": "01:20",
          "endTime": "01:25",
          "text": "I don't know, it just wasn't really happening. Okay, so it sounds like you were trying to work hard and",
          "sentiment": "Resignation"
        },
        {
          "startTime": "01:25",
          "endTime": "01:30",
          "text": "yeah, um, be more successful because you thought that that would make them happier and",
          "sentiment": "Sadness"
        },
        {
          "startTime": "01:30",
          "endTime": "01:35",
          "text": "try and fix things. Yeah, I wanted to make them feel better but it",
          "sentiment": "Guilt"
        },
        {
          "startTime": "01:35",
          "endTime": "01:40",
          "text": "just kind of backfired a little I guess. How did it backfire?",
          "sentiment": "Shame"
        },
        {
          "startTime": "01:40",
          "endTime": "01:48",
          "text": "Well, it just ended up with them getting worse and I've just been feeling worse since then.",
          "sentiment": "Grief"
        }
      ],
      "mismatches": [
        {
          "timestamp": "00:05",
          "visualEmotion": "Neutral",
          "verbalEmotion": "Frustration",
          "severity": "LOW"
        },
        {
          "timestamp": "00:20",
          "visualEmotion": "Joy",
          "verbalEmotion": "Guilt",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "00:26",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "LOW"
        },
        {
          "timestamp": "00:30",
          "visualEmotion": "Joy",
          "verbalEmotion": "Resignation",
          "severity": "LOW"
        },
        {
          "timestamp": "00:35",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "00:45",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anxiety",
          "severity": "LOW"
        },
        {
          "timestamp": "00:50",
          "visualEmotion": "Joy",
          "verbalEmotion": "Anxiety",
          "severity": "LOW"
        },
        {
          "timestamp": "00:55",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "01:01",
          "visualEmotion": "Joy",
          "verbalEmotion": "Shock",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "01:06",
          "visualEmotion": "Joy",
          "verbalEmotion": "Guilt",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "01:11",
          "visualEmotion": "Joy",
          "verbalEmotion": "Guilt",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "01:16",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "LOW"
        },
        {
          "timestamp": "01:21",
          "visualEmotion": "Joy",
          "verbalEmotion": "Resignation",
          "severity": "LOW"
        },
        {
          "timestamp": "01:26",
          "visualEmotion": "Joy",
          "verbalEmotion": "Sadness",
          "severity": "LOW"
        },
        {
          "timestamp": "01:31",
          "visualEmotion": "Joy",
          "verbalEmotion": "Guilt",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "01:36",
          "visualEmotion": "Joy",
          "verbalEmotion": "Shame",
          "severity": "MEDIUM"
        },
        {
          "timestamp": "01:41",
          "visualEmotion": "Joy",
          "verbalEmotion": "Grief",
          "severity": "HIGH"
        }
      ],
      "overallSummary": "The speaker frequently exhibits brief, almost forced smiles while discussing difficult and painful topics, such as feeling guilty, not wanting to bring friends down, hiding feelings, parental troubles, and personal struggles at university. This suggests a pattern of masking underlying sadness, guilt, and anxiety with a superficial positive expression. The discrepancy between her verbal expressions of distress and her fleeting smiles indicates an internal conflict, possibly an attempt to cope or minimize the emotional impact of her experiences. The severity of these mismatches increases towards the end of the conversation, particularly when discussing the negative outcomes of her efforts and her worsening emotional state."
    }
  }
};
